name: flutter_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  get: ^4.6.6
  ping_discover_network_v2: ^0.0.2
  network_info_plus: ^4.1.0
  device_info_plus: 9.1.2
  go_router: ^14.2.3
  get_it: ^7.7.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2

dev_dependencies:
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
